version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=pitchscoop
      - MINIO_SECRET_KEY=pitchscoop123
      - MINIO_BUCKET_NAME=pitchscoop
      - SYSTEM_LLM_AZURE_ENDPOINT=${SYSTEM_LLM_AZURE_ENDPOINT}
      - SYSTEM_LLM_AZURE_API_KEY=${SYSTEM_LLM_AZURE_API_KEY}
      - SYSTEM_LLM_AZURE_DEPLOYMENT=${SYSTEM_LLM_AZURE_DEPLOYMENT}
      - SYSTEM_LLM_AZURE_API_VERSION=${SYSTEM_LLM_AZURE_API_VERSION}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - redis
      - minio
      - qdrant
    networks:
      - hackathon-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - hackathon-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"      # API
      - "9001:9001"      # Console
    environment:
      - MINIO_ACCESS_KEY=pitchscoop
      - MINIO_SECRET_KEY=pitchscoop123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - hackathon-net

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"      # HTTP API
      - "6334:6334"      # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - hackathon-net

volumes:
  redis-data:
  minio-data:
  qdrant-data:

networks:
  hackathon-net:
    driver: bridge
